### ISSUE TITLE
React - MwCard customization

### ISSUE THREAD

**Issue by SohaiebAzMaibornwolff** [MaibornWolff/mwui#110]
Hello Mw Team, 

-  **Problem:**

I use MwUi for React, I could not be able to customize the card element to fit to our needs. 
One of things I want to do is to fit the width of the card container to follow its parent. 

- **Suggestion:** 

to solve this issue, you may either add the possibility to add customizable properties to add custom css classes to the containers , or to use [Html](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/part)/[Css](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) Element [Part Attribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/part), this would help developers to have almost a full css control.

thank you.

**Comment by Fuasmattn** [comment]
thanks for the feedback and suggestion. We'll look into it and do the required improvements asap :)

**Comment by Fuasmattn** [comment]
so the card has some max-width in place. If your issue is with going bigger than this value (600px) we need to change something as suggested. But if it's about smaller sizes, it should be able to follow the container, if the width is also set on mw-card like:

```
<some-layout-div style="width: 200px" >
  <mw-card style="width: 100%" />
</some-layout-div>
```

**Comment by SohaiebAzMaibornwolff** [comment]
> so the card has some max-width in place. If your issue is with going bigger than this value (600px) we need to change something as suggested. But if it's about smaller sizes, it should be able to follow the container, if the width is also set on mw-card like:
> 
> ```
> <some-layout-div style="width: 200px" >
>   <mw-card style="width: 100%" />
> </some-layout-div>
> ```

To be honest yes, it's about going bigger than 600px , 
we want the card to fit to 100% of its parent container (in our case it's our Window Width) 
It would be also great if we base on classNames instead of using style attribute, because we use other CSS framework pre-implemented classes

**Comment by Fuasmattn** [comment]
you can also use css classes, I just did it inline for that code snippet. Custom elements can be treated as any other standard HTML element. With the exception for the shadow DOM. So adding `parts` to the container could be an option. however I'd like to reach out to our designers if the max-width should be able to be broken.

For what use case are you using a card in fullscreen?

**Comment by Fuasmattn** [comment]
tbh I think that would be not the correct use of a card. But also, we are not very specific yet on the documentation side when and how to use specific components

**Comment by SohaiebAzMaibornwolff** [comment]
> tbh I think that would be not the correct use of a card. But also, we are not very specific yet on the documentation side when and how to use specific components

well Maybe i was not specific : the use case needs to implement a page container with header, body and footer, which also implement some of the Card design we need, that's why we though to use it instead of reimplemented the hole container from scratch

**Comment by Fuasmattn** [comment]
ok, then I can tell this is not the way it should be used. the mw-card is not meant to be a page layout component.
to cite MUI: _"Cards are surfaces that display content and actions on a single topic."_

**Comment by Fuasmattn** [comment]
Unlike libraries like bootstrap, material-ui or similar, MWUI is a **branded component library** as part of a design system. Therefore the intention is to have a consistent look and feel across internal applications, determined by the Design System. Customising the mwui library in a way like changing colours is contradicting with this idea.
