### ISSUE TITLE
Hover State on Buttons

### ISSUE THREAD

**Issue by philipbrembeck** [MaibornWolff/mwui#178]
**Describe the solution you'd like**
Buttons currently do have Hover / Active states, but unfortunately there is no transition happening. 
Something like `transition: all .2s ease-in-out` would be really nice to have.

**Comment by Fuasmattn** [comment]
That's true, we haven't aligned any general transitions and animations yet, therefore didn't focus on it. However, there are some, e.g. in modals (so this is not entirely true) I will push that topic so we have at least some basic transitions like for the button states. Thanks for raising this!

**Comment by Fuasmattn** [comment]
Changes are on its way.
Pull Request: https://github.com/MaibornWolff/mwui/pull/179
PR storybook: https://643feeb210a18ce271248cc6-unkzcudaul.chromatic.com/?path=/story/components-button--filled
