### ISSUE TITLE
[Feat] File Input Field

### ISSUE THREAD

**Issue by philipbrembeck** [MaibornWolff/mwui#183]
**Describe the solution you'd like**
Currently, no file input field is available. I would like to have 
  a) A drop zone for file-inputs
  b) File input fields in the MWUI style

**Comment by Fuasmattn** [comment]
There is no planned design yet for a sophisticated file input element. However, the next release with contain styling for html input elements (except for types range, checkbox and radio). So, the <input type="file" /> should work (also with dropping items to it).

**Comment by Fuasmattn** [comment]
latest release for mwui-stencil contains global css adding styling to HTML file input fields. A Web Component for more elaborated version is requested for designers. Will close this issue for now
