### ISSUE TITLE
[Bug] Behaviour/Style of Switch buttons seems off

### ISSUE THREAD

**Issue by philipbrembeck** [MaibornWolff/mwui#184]
**Is your feature request related to a problem? Please describe.**
The Switch button looks not like it is supposed to be. Next.js project @latest und NodeJS 20.

![Screen Recording 2023-06-29 at 14 51 59](https://github.com/MaibornWolff/mwui/assets/4144601/9f68ab4b-3c91-4e98-9fcc-a26bfd5749d1)

The onClick function also does not seem to work on the switch Component:
```typescript
onClick={() => {
            if (filterLinks) {
              setFilterLinks(false);
            } else {
              setFilterLinks(true);
            }
          }}
```
This has no effect, while it has an effect on any other component that can take onClick handlers.

**Comment by Fuasmattn** [comment]
Recently fixed the styling issue. Will have a look at the event. 
Would you expect a click event or a change event for a switch?

**Comment by philipbrembeck** [comment]
I think `onChange` would be appropriate, but for a more complete solution, `onClick` should also be implemented.
