### ISSUE TITLE
Add Link component

### ISSUE THREAD

**Issue by Fuasmattn** [MaibornWolff/mwui#29]

**Comment by Fuasmattn** [comment]
@m-m-mic  I think the component needs options for `target` (see https://www.w3schools.com/tags/tag_a.asp) and another prop to disable the text-decoration underline. The last one could be needed when using an icon as a link. currently the icon will have an underline

**Comment by m-m-mic** [comment]
Added both target and underline prop in commit 2a72ad8a7b4b08a89a8a9da2e4ea179eacf4177e

**Comment by Dennis-MW** [comment]
- the default link has no underline even if i set the boolean to true

**Comment by m-m-mic** [comment]
@Dennis-MW there used to be a token for the underline which has seemingly been removed (mw-component-link-type-text-decoration). I've hardcoded the underline for now, but the token should probably be added back.
