### ISSUE TITLE
Add Login component (molecule)

### ISSUE THREAD

**Issue by leChuckles** [MaibornWolff/mwui#58]

**Comment by stefanrie** [comment]
- Text align center for the headline
- Add spacing below overline (2px)
- Change color of input text for textfield from #000000 to #44555B
- If selected the icon in the checkbox is not center aligned
- Do not color icons at the end of input field if active
- Adapt colors of typography

**Comment by m-m-mic** [comment]
@stefanrie currently working on this and I have a few questions in regards to your review:
- (2nd point) which overline do you mean exactly?
- (3rd & 6th point) currently tied to tokens, so shouldn't the tokens be changed instead to make this change?
- (5th point) the colour of the icons when focused is also tied to a figma token, so I think it's preferable to change the token instead if the icons aren't supposed to change colour
