### ISSUE TITLE
Add stencil integration for Angular and Vue

### ISSUE THREAD

**Issue by Fuasmattn** [MaibornWolff/mwui#7]
- https://stenciljs.com/docs/angular
- https://stenciljs.com/docs/vue

**Comment by m-m-mic** [comment]
- [ ] Vue integration
- [ ] Angular integration

Issues:
- The angular integration doesn't work properly. Angular seems to be able to identify the component but its contents aren't rendered at all.

**Comment by leChuckles** [comment]
PR is merged to main - but should still be tested that everything works after publish on npm
